CREATE SEQUENCE HIBERNATE_SEQUENCE START 1 INCREMENT 1;

CREATE SEQUENCE USER_SEQ START 1000 INCREMENT 1;

CREATE TABLE REVINFO (
	REV 				INT4				NOT NULL,
 	REVTSTMP			INT8						, 
	PRIMARY KEY (REV)
);

CREATE TABLE USER (
	USER_ID 			INT8 				NOT NULL,
    USER_NAME 			VARCHAR(255) 		NOT NULL,
    PASSWORD			VARCHAR(255)		NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_AUD (
	USER_ID 			INT8 				NOT NULL,
    USER_NAME 			VARCHAR(255) 				,
    PASSWORD			VARCHAR(255)				,
    REV					INT4				NOT NULL,
    REVTYPE				INT2						, 
    PRIMARY KEY (USER_ID, REV)
);

ALTER TABLE IF EXISTS USER_AUD ADD CONSTRAINT FK_USER_AUD_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO;